### ISSUE TITLE
Address book should update via the app

### ISSUE THREAD

**Issue by rbultman** [rbultman/raspberry-jam#16]
The address currently needs to be edited by hand, either on the pi itself or off-pi and then transferred back to it.  The address book functionality should be changes as follows:

- Names and ip addresses can be added, edited, and deleted via the app
- A "jam" configuration consisting of a number of users from the address book, bit rate, etc, can be saved and named.  This will allow a configuration to be easily recalled.

**Comment by gillspice** [comment]
Included in release 1.2
