### ISSUE TITLE
Update sound card guide with Alsa Mixer details

### ISSUE THREAD

**Issue by rbultman** [rbultman/raspberry-jam#39]
Update the section on Alsa Mixer commands in the [guide for adding a new sound card](https://github.com/rbultman/raspberry-jam/wiki/Adding-a-New-Sound-Card).

Each sound card is different and requires different Alsa Mixer commands to control it.  Please update the section to who people how to figure out what the commands are.

**Comment by gillspice** [comment]
Done.  Regarding finding the correct overlay, why not suggest getting that info from the manufacturer?

**Comment by rbultman** [comment]
Good idea.  I'll update that section.
