### ISSUE TITLE
Add realtime kernel for Pi 3 in addition to Pi 4 to image

### ISSUE THREAD

**Issue by gillspice** [rbultman/raspberry-jam#4]
Add realtime kernel for Pi 3 in addition to Pi 4 to image

**Comment by CAguayo** [comment]
Very interested in this project, and I should be able to contribute significantly once I get rolling, but my RPi foo is more than a little out of date.  Could you post a bit more context for getting started, like a link to the base image you're starting with, and RT kernel info?

**Comment by rbultman** [comment]
Hey Carlos, welcome!  We will be posting an image soon, we just have some cleanup work to do on it.  If you look in the ['steps' section of this wiki page](https://github.com/rbultman/raspberry-jam/wiki/Custom-Pi-Image-Notes), it lists the rough steps I used to create the RT kernel for the pi4.  We have been able to verify it works from a few different locations with two endpoints.  WFIW, you don't need RT kernel to get connectivity.  At this point, I don't know that you gain a ton from it, at least on the Pi4.

**Comment by CAguayo** [comment]
Thanks, Rob, I'll have a look at the wiki.  I'm wondering if USB is an
option, I have a (rev 2?) RPi board that I'm thinking of spinning up even
ahead of ordering an audio card, and the plantronics usb interface is
actually pretty good.

Thanks for pushing this along so quickly!  I know a lot of people are very
interested in this functionality, and it would be super cool to make it
real!

Carlos
caguayo@gmail.com

**Comment by rbultman** [comment]
Hey Carlos, if it is supported by alsa, it should work just fine.  Just plug it into the pi, open alsa mixer (alsamixer) and see if you can select it using the F6 key on your keyboard.  If you can see it, exit alsa mixer and try to use jackd to connect your input to your output.

**Comment by rbultman** [comment]
Implemented in image release v1.0
