### ISSUE TITLE
Default sound config in image

### ISSUE THREAD

**Issue by gillspice** [rbultman/raspberry-jam#5]
I think what makes sense for the image, by default is to have the internal sound disabled, with as many of the dtoverlays for suggested cards prepopulated in the confing.txt only commented out.  Then all a user would have to do would be to uncomment the one they have.

**Comment by gillspice** [comment]
dtoverlay=fe-pi-audio
dtoverlay=audioinjector-wm8731-audio
dtoverlay=audioinjector-ultra
dtoverlay=pisound 
dtoverlay=hifiberry-dacplusadcpro
dtoverlay=hifiberry-dacplusadc
dtoverlay=hifiberry-dac

**Comment by rbultman** [comment]
Implemented in image release v1.0
